// Code generated by protoc-gen-go.
// source: header.proto
// DO NOT EDIT!

package pb

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Header struct {
	Length           *uint64 `protobuf:"fixed64,1,req,name=length" json:"length,omitempty"`
	CheckSum         *uint32 `protobuf:"fixed32,2,req,name=checkSum" json:"checkSum,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}

func (m *Header) GetLength() uint64 {
	if m != nil && m.Length != nil {
		return *m.Length
	}
	return 0
}

func (m *Header) GetCheckSum() uint32 {
	if m != nil && m.CheckSum != nil {
		return *m.CheckSum
	}
	return 0
}

func init() {
}
