// Code generated by protoc-gen-go.
// source: module.proto
// DO NOT EDIT!

package pb

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Module int32

const (
	Module_UNKNOWN  Module = 0
	Module_RESPONSE Module = 1
	Module_SIGN_UP  Module = 2
	Module_SIGN_IN  Module = 3
)

var Module_name = map[int32]string{
	0: "UNKNOWN",
	1: "RESPONSE",
	2: "SIGN_UP",
	3: "SIGN_IN",
}
var Module_value = map[string]int32{
	"UNKNOWN":  0,
	"RESPONSE": 1,
	"SIGN_UP":  2,
	"SIGN_IN":  3,
}

func (x Module) Enum() *Module {
	p := new(Module)
	*p = x
	return p
}
func (x Module) String() string {
	return proto.EnumName(Module_name, int32(x))
}
func (x *Module) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Module_value, data, "Module")
	if err != nil {
		return err
	}
	*x = Module(value)
	return nil
}

func init() {
	proto.RegisterEnum("pb.Module", Module_name, Module_value)
}
