// Code generated by protoc-gen-go.
// source: request.proto
// DO NOT EDIT!

package pb

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

// module : field = n : 1
type Request struct {
	Module           *Module `protobuf:"varint,1,req,name=module,enum=pb.Module" json:"module,omitempty"`
	Sign             *Sign   `protobuf:"bytes,3,opt,name=sign" json:"sign,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}

func (m *Request) GetModule() Module {
	if m != nil && m.Module != nil {
		return *m.Module
	}
	return Module_UNKNOWN
}

func (m *Request) GetSign() *Sign {
	if m != nil {
		return m.Sign
	}
	return nil
}

func init() {
}
